# https://www.mkdocs.org/
site_name: Prime Backup Documentation
site_url: https://tisunion.github.io/PrimeBackup/
site_author: Fallen_Breath
site_description: A powerful backup plugin for MCDR, an advanced backup solution for your Minecraft world
repo_url: https://github.com/TISUnion/PrimeBackup
repo_name: TISUnion/PrimeBackup
copyright: Copyright &copy; 2025 Fallen_Breath
exclude_docs: |-
  /requirements.txt

# https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/
markdown_extensions:
  - admonition
  - toc:
      permalink: true
      slugify:
        # https://github.com/mkdocs/mkdocs/issues/212#issuecomment-286035214
        # pymdownx.slugs.uslugify is deprecated, let's use the modern way
        !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower

  # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
  # https://squidfunk.github.io/mkdocs-material/reference/icons-emojis/#configuration
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  # https://mkdocs-mermaid2.readthedocs.io/en/latest/#use-of-the-material-theme
  - pymdownx.superfences:
      # make exceptions to highlighting of code:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid_custom
theme:
  name: material
  features:
    - content.code.copy
    - navigation.expand
    - navigation.path
    - navigation.prune
    - navigation.top
  # https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#automatic-light-dark-mode
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

plugins:
  - i18n:
      # https://ultrabug.github.io/mkdocs-static-i18n/getting-started/quick-start/#configure-the-plugin-in-your-mkdocsyml
      docs_structure: suffix
      languages:
        - locale: en
          name: English
          build: true
          default: true
        - locale: zh
          name: 简体中文
          build: true
          # translations:
          site_name: Prime Backup 文档
          nav_translations:
            Reference: 参考
  - macros
  # https://mkdocs-mermaid2.readthedocs.io/
  - mermaid2:
      javascript: js/mermaid-10.8.0.min.js
  - mkdocs-simple-hooks:
      hooks:
        on_post_build: docs.build_hooks:on_post_build
  - search

nav:
  - index.md
  - quick_start.md
  - config.md
  - command.md
  - cli.md
  - Reference:
    - reference/index.md
